---
- name: Set hostname as fqdn
  hostname: name={{ foreman_hostname }}
  when: foreman_hostname is defined

- name: Copy script to modify /etc/hosts
  copy:
    src: mungehosts
    dest: /usr/local/bin/mungehosts
    mode: 0755

- name: Resolve hostname via /etc/hosts to resolve `hostname -f`
  #lineinfile: dest=/etc/hosts line="{{ansible_default_ipv4.address}} {{ansible_fqdn}} {{ansible_hostname}}"
  #command: python /tmp/modify_hosts.py "{{ansible_default_ipv4.address}}", "{{ansible_default_ipv4.address}} {{ansible_hostname}}"
  command: /usr/local/bin/mungehosts -a "{{ansible_default_ipv4.address}} {{foreman_hostname}}"
  when: foreman_hostname is defined

- name: Update CA Certificate
  apt:
    name: ca-certificates
    update_cache: yes

- name: Install Puppet Repository
  apt:
    deb: https://apt.puppetlabs.com/{{puppet_version}}-release-{{ansible_distribution_release}}.deb

- name: Install Foreman Repository
  block:
    - name: Add Public Key
      apt_key:
        url: https://deb.theforeman.org/pubkey.gpg
        state: present
    - name: Install Foreman Repo
      apt_repository:
        repo: deb http://deb.theforeman.org/ {{ansible_distribution_release}} {{foreman_version}}
        state: present
        filename: /etc/apt/sources.list.d/foreman.list
    - name: Install Foreman Plugin Repo
      apt_repository:
        repo: deb http://deb.theforeman.org/ plugins {{foreman_version}}
        state: present
        filename: /etc/apt/sources.list.d/foreman_plugins.list

- name: Download foreman installer package
  apt: name=foreman-installer force=yes update_cache=yes

- name: Install puppet agent
  apt: name=puppet-agent force=yes update_cache=yes
  when: disable_puppet | bool

- name: Install and Configure foreman without puppet
  block:
    - name: Install foreman without puppet
      command: >
        foreman-installer
        --foreman-unattended=true
        --foreman-db-manage={{ foreman_db_manage | bool | lower }}
        --foreman-db-type={{ foreman_db_type }}
        --foreman-db-host={{ foreman_db_host }}
        --foreman-db-database={{ foreman_db_database }}
        --foreman-db-username={{ foreman_db_username }}
        --foreman-db-password={{ foreman_db_password }}
        --foreman-admin-username={{ foreman_admin_username }}
        --foreman-admin-password={{ foreman_admin_password }}
        --puppet-server=false --foreman-proxy-puppet=false --foreman-proxy-puppetca=false
        {{foreman_cmd_options | join (' ')}}
  when: disable_puppet | bool

- name: Install and Configure Foreman with Puppet
  block:
    - name: Install foreman with Puppet
      command: >
        foreman-installer
        --foreman-unattended=true
        --enable-foreman --enable-foreman-cli --enable-foreman-proxy
        --foreman-db-manage={{ foreman_db_manage | bool | lower }}
        --foreman-db-type={{ foreman_db_type }}
        --foreman-db-database={{ foreman_db_database }}
        --foreman-db-username={{ foreman_db_username }}
        --foreman-db-password={{ foreman_db_password }}
        --foreman-admin-username={{ foreman_admin_username }}
        --foreman-admin-password={{ foreman_admin_password }}
        {{foreman_cmd_options | join (' ')}}
  when: disable_puppet == false


